//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Charades.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary
    {
        public Dictionary()
        {
            this.Word = new HashSet<Word>();
        }
    
        public int DictionaryId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Word> Word { get; set; }
    }
}
