//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Charades.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Word
    {
        public int WordId { get; set; }
        public string Name { get; set; }
        public int DictionaryId { get; set; }
        public Nullable<int> LevelId { get; set; }
    
        public virtual Dictionary Dictionary { get; set; }
        public virtual Level Level { get; set; }
    }
}
